export const LOAD_USERS_REQUEST = 'LOAD_USERS_REQUEST';
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const GENERATE_LIST = 'GENERATE_LIST';
export const CHANGE_FILTER = 'CHANGE_FILTER';
export const FILTER_USERS = 'FILTER_USERS';
export const CHANGE_PAGE = 'CHANGE_PAGE';